### PR TITLE
i18n & linux command copy

### PR DESCRIPTION
**Pull request by ArsFy**
1. i18n support:
    - DE
    - EN
    - ES
    - FR
    - RU
    - zh-CN
    - zh-HK
2. Add new system: Binary (linux command)
3. Windows: `Ctrl K`

### CODE REVIEW

**Comment by henrygd** [comment]
Amazing, thank you so much!

It's 10pm where I am so I'll check this out tomorrow. Possibly not until the afternoon.

**Comment by henrygd** [comment]
@ArsFy  I really appreciate this. That was a lot of work and I'm extremely thankful.

We have a few areas still to translate, but they are minor and don't necessarily need to be done now.

Thanks for setting up the project on Crowdin. I'm fine with you owning the project if you want to, or you can transfer it to me if you don't want it to count against your account limits. I need to be added as an admin or manager, though.

Alternatively, we can move to Weblate and I can invite you as an admin. That would give us higher limits. Seems to be compatible with the current setup as well.

**Comment by ArsFy** [comment]
@henrygd Okay, let's move the project to Weblate. However, there is a link to Crowdin in general.tsx:53 that needs to be changed after the project is moved.

My Weblate username is @Arsfy

**Comment by henrygd** [comment]
@ArsFy Just added you as an admin on Weblate.

The stuff in there currently is a test scan I did on the repo.

I think we'll need to delete it and rescan after we get the fresh translations from Crowdin added to the repo.

Including the Ukrainian translations from @alexzaitsev  (thank you!).

**Comment by ArsFy** [comment]
@henrygd I will directly delete the Crowdin project. The latest translations are actually in my repo, and I have added some features. I will create a new merge request to add the new features (note that I haven't modified the links pointing to Crowdin in the code, you might need to do that as I forgot about it)

If he can provide the Ukrainian translation, that would be great. Please upload it to the new Weblate project, and I will take care of the rest.

**Comment by ArsFy** [comment]
@henrygd In fact, I have never used Weblate before. If I modify the JSON in the repo, will Weblate automatically update? 🤔

**Comment by henrygd** [comment]
@ArsFy Looks like it can: https://docs.weblate.org/en/latest/admin/continuous.html#automatically-receiving-changes-from-github

I need to set that up, which will be tomorrow at earliest because it's lat here.

I think you can manually pull changes for now. We should just delete what I have in there and start over.

**Comment by henrygd** [comment]
FYI - I just pushed Japanese, Vietnamese, and Arabic (need to check RTL) to the repo.

Alex added Ukrainian translations to Crowdin but I didn't grab them before the project was deleted.

**Comment by ArsFy** [comment]
@henrygd He added it to crowdin? I'm really sorry that this is my problem. I didn't confirm whether any translation was added. I hope he has a copy of the translation 😭

**Comment by henrygd** [comment]
@ArsFy Don't sweat it, they can always be recreated.

@alexzaitsev Any chance you saved a local copy of your translations?

**Comment by alexzaitsev** [comment]
LOL guys I haven't saved it locally!
It was a great project to contribute but you won't get too far discarding a few hours of other's work.

**Comment by alexzaitsev** [comment]
I was working on https://github.com/henrygd/beszel/issues/219 btw. I see it's fixed in this release. Is there any assignment mechanism so I can assign the bug I'm working on to myself?

**Comment by henrygd** [comment]
@alexzaitsev Our apologies. I can understand your frustration. We hadn't finalized what platform we were going to use for localization, and ArsFy didn't know that I'd shared the preview site with anyone else.

It's regrettable, but the mistake was due to miscommunication and not malice. We'll add machine translations for Ukrainian to start with. That way it doesn't need to be translated from scratch if someone wants to improve them.

---

I agree that it should be clearer what work is completed or in progress. I've created an "in progress" label that I'll start adding to issues which are being worked on. I'll also try to be more proactive about including issue tags in commit messages and closing issues when development is done.

For you and others, I think the best thing to do is make a comment in the issue saying "I'll try to work on this" or something like that. Then I can also assign it to you.

If it's not assigned to anyone, and not clear from the context who will work on it, it will be me eventually.

**Comment by ArsFy** [comment]
I'm very, very sorry @alexzaitsev, I thought the Crowdin project had not been shared. I understand that several hours of work are very important to you, and I highly value others' work. Please allow me to apologize once again.

I don’t speak Ukrainian, so I have no way to complete this part with high quality. However, I would like to make it up to you. I’m not sure what I can do, but please let me know if there’s anything I can help with.

**Pull request merged**
