### PR TITLE
Enhanced README.md

### PR DESCRIPTION
**Pull request by crypt0rr**
Hi @henrygd - here some minor changes to enhance the `README.md`. Keep the good work up!

- Changed some wording to make it a bit clearer
- CamelCase headings
- Added License reference

### CODE REVIEW

**Comment by henrygd** [comment]
Thanks, I like the changes. Just two things:

1. I'd prefer to standardize headings using sentence case rather than title case.
2. The bit about Authelia is meant to convey that adding a custom authentication gateway won't interfere with the connection between the hub and agent -- i.e., cause them to disconnect. The wording could be better there to express that. I can update it afterward if you're not sure.

**Comment by crypt0rr** [comment]
Cool, let me change that tomorrow!

**Comment by crypt0rr** [comment]
@henrygd I fixed both your comments 👍🏼

**Comment by henrygd** [comment]
Merged, thanks :+1:

**Pull request merged**
